joomla:
  image: joomla
  links:
    - joomladb:mysql
  ports:
    - 9090:80
  volumes:
    - ./www:/var/www/html

joomladb:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: password
  volumes:
    - ./mysql:/var/lib/mysql

phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - joomladb:mysql
  ports:
    - 8181:80
  environment:
    MYSQL-USERNAME: root
    MYSQL_ROOT_PASSWORD: password